rootcolor=0x151217ff
bordercolor=0x4b454dff
focuscolor=0xddb9f8ff
urgentcolor=0xffb4abff
scratchpadcolor=0x221e24ff
maximizescreencolor=0xddb9f8ff
globalcolor=0xf3b7bcff
overlaycolor=0xd1c1d9ff
shadowscolor=0x00000055
