rootcolor=0x151218ff
bordercolor=0x4a454eff
focuscolor=0xd7bafbff
urgentcolor=0xffb4abff
scratchpadcolor=0x211e24ff
maximizescreencolor=0xd7bafbff
globalcolor=0xf2b7c1ff
overlaycolor=0xcfc2daff
shadowscolor=0x00000055
