[opener]
nsxiv_browse_dir = [
    { run = 'nsxiv_browse_dir "$@"', orphan = true },
]

[open]
prepend_rules = [
    { mime = "image/*", use = "sxiv_browse_dir" },
]

[plugin.previewer]
archive = true
